name: Test envs in building docker

on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: avkarcr/docker-build-envs:latest
        build-args: |
          MY_SECRET=${{ secrets.MY_SECRET }}
